In [1]:
import os
import sys
nb_dir = os.path.split(os.getcwd())[0]
if nb_dir not in sys.path:
    sys.path.append(nb_dir)

from Game import *

In [5]:
t2 = MCRLTournament()
t2.run_tournament(3000, 300)
t2.print_buy_history()

# pickle_safe(t2.player.strategy.q, 'qsave')
# pickle_safe(t2.player.strategy.c, 'csave')

100%|██████████| 3000/3000 [06:28<00:00,  7.72it/s]


Turn 1
Province 0   Duchy 0   Estate 0   Gold 0   Silver 274   Copper 0   Lab 0   Smithy 0   Village 0   NoCard 26   
Turn 2
Province 0   Duchy 0   Estate 0   Gold 0   Silver 149   Copper 23   Lab 0   Smithy 128   Village 0   NoCard 0   
Turn 3
Province 0   Duchy 0   Estate 0   Gold 63   Silver 227   Copper 0   Lab 0   Smithy 0   Village 0   NoCard 10   
Turn 4
Province 0   Duchy 0   Estate 0   Gold 83   Silver 43   Copper 0   Lab 0   Smithy 164   Village 0   NoCard 10   
Turn 5
Province 0   Duchy 0   Estate 0   Gold 134   Silver 74   Copper 0   Lab 87   Smithy 0   Village 0   NoCard 5   
Turn 6
Province 0   Duchy 0   Estate 0   Gold 173   Silver 58   Copper 0   Lab 67   Smithy 0   Village 0   NoCard 2   
Turn 7
Province 0   Duchy 0   Estate 0   Gold 194   Silver 19   Copper 0   Lab 0   Smithy 81   Village 0   NoCard 6   
Turn 8
Province 123   Duchy 0   Estate 0   Gold 95   Silver 33   Copper 0   Lab 48   Smithy 0   Village 0   NoCard 1   
Turn 9
Province 137   Duchy 0   Estate 0   Gol

In [6]:
print(t2.player.strategy.prio_buys)

[Province, Duchy, NoCard, Estate, Copper, Village, Silver, Smithy, Lab, Gold]


In [10]:
pickle_safe(t2.player.strategy.q, 'firstqsave')
pickle_safe(t2.player.strategy.c, 'firstcsave')

In [2]:
loadedq = pickle_load('qsave')
loadedc = pickle_load('csave')

t3 = MCRLTournament(loadedq, loadedc)
t3.last_epoch(100)

In [3]:
a = np.zeros((5,3))
a[1,2] += 4
print(a)

[[0. 0. 0.]
 [0. 0. 4.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [9]:
# buy_at_turn = {}

# for i in range(4):
#     buy_at_turn[i] = [0] * 5

buy_at_turn = {i:[0]*5 for i in range(4)}

print(buy_at_turn)

{0: [0, 0, 0, 0, 0], 1: [0, 0, 0, 0, 0], 2: [0, 0, 0, 0, 0], 3: [0, 0, 0, 0, 0]}


In [3]:
a = 3
b = [i for i in range(-a,a)]
print(b)

[-3, -2, -1, 0, 1, 2]
